import * as React from "react";
import * as System from "@material-ui/core";
import { ControlType, PropertyControls, addPropertyControls } from "framer";

const style: React.CSSProperties = {
  width: "100%",
  height: "100%"
};

export const GridListTile: React.SFC = props => {
  return <System.GridListTile {...props} style={style} />;
};

GridListTile.defaultProps = {
  width: 150,
  height: 50
};

addPropertyControls(GridListTile, {
  cols: { title: "Cols", type: ControlType.Number },
  component: {
    title: "Component",
    options: [
      "abbr",
      "address",
      "article",
      "aside",
      "b",
      "bdi",
      "bdo",
      "big",
      "blockquote",
      "caption",
      "cite",
      "code",
      "data",
      "dd",
      "del",
      "details",
      "dfn",
      "dt",
      "em",
      "figcaption",
      "figure",
      "footer",
      "head",
      "header",
      "hgroup",
      "i",
      "kbd",
      "keygen",
      "li",
      "main",
      "mark",
      "menu",
      "menuitem",
      "meter",
      "nav",
      "noindex",
      "noscript",
      "output",
      "picture",
      "rp",
      "rt",
      "ruby",
      "s",
      "samp",
      "section",
      "small",
      "span",
      "strong",
      "sub",
      "summary",
      "sup",
      "time",
      "u",
      "var",
      "wbr",
      "webview"
    ],
    optionTitles: [
      "Abbr",
      "Address",
      "Article",
      "Aside",
      "B",
      "Bdi",
      "Bdo",
      "Big",
      "Blockquote",
      "Caption",
      "Cite",
      "Code",
      "Data",
      "Dd",
      "Del",
      "Details",
      "Dfn",
      "Dt",
      "Em",
      "Figcaption",
      "Figure",
      "Footer",
      "Head",
      "Header",
      "Hgroup",
      "I",
      "Kbd",
      "Keygen",
      "Li",
      "Main",
      "Mark",
      "Menu",
      "Menuitem",
      "Meter",
      "Nav",
      "Noindex",
      "Noscript",
      "Output",
      "Picture",
      "Rp",
      "Rt",
      "Ruby",
      "S",
      "Samp",
      "Section",
      "Small",
      "Span",
      "Strong",
      "Sub",
      "Summary",
      "Sup",
      "Time",
      "U",
      "Var",
      "Wbr",
      "Webview"
    ],
    type: ControlType.Enum
  },
  rows: { title: "Rows", type: ControlType.Number }
});
