import * as React from "react";
import * as System from "@material-ui/core";
import { ControlType, PropertyControls, addPropertyControls } from "framer";

const style: React.CSSProperties = {
  width: "100%",
  height: "100%"
};

export const InputBase: React.SFC = props => {
  return <System.InputBase {...props} style={style} />;
};

InputBase.defaultProps = {
  width: 150,
  height: 50
};

addPropertyControls(InputBase, {
  autoComplete: { title: "AutoComplete", type: ControlType.String },
  autoFocus: { title: "AutoFocus", type: ControlType.Boolean },
  disabled: { title: "Disabled", type: ControlType.Boolean },
  error: { title: "Error", type: ControlType.Boolean },
  fullWidth: { title: "FullWidth", type: ControlType.Boolean },
  id: { title: "Id", type: ControlType.String },
  inputComponent: {
    title: "InputComponent",
    options: [
      "abbr",
      "address",
      "article",
      "aside",
      "b",
      "bdi",
      "bdo",
      "big",
      "blockquote",
      "caption",
      "cite",
      "code",
      "data",
      "dd",
      "del",
      "details",
      "dfn",
      "dt",
      "em",
      "figcaption",
      "figure",
      "footer",
      "head",
      "header",
      "hgroup",
      "i",
      "input",
      "kbd",
      "keygen",
      "main",
      "mark",
      "menu",
      "menuitem",
      "meter",
      "nav",
      "noindex",
      "noscript",
      "output",
      "picture",
      "rp",
      "rt",
      "ruby",
      "s",
      "samp",
      "section",
      "small",
      "span",
      "strong",
      "sub",
      "summary",
      "sup",
      "textarea",
      "time",
      "u",
      "var",
      "wbr",
      "webview"
    ],
    optionTitles: [
      "Abbr",
      "Address",
      "Article",
      "Aside",
      "B",
      "Bdi",
      "Bdo",
      "Big",
      "Blockquote",
      "Caption",
      "Cite",
      "Code",
      "Data",
      "Dd",
      "Del",
      "Details",
      "Dfn",
      "Dt",
      "Em",
      "Figcaption",
      "Figure",
      "Footer",
      "Head",
      "Header",
      "Hgroup",
      "I",
      "Input",
      "Kbd",
      "Keygen",
      "Main",
      "Mark",
      "Menu",
      "Menuitem",
      "Meter",
      "Nav",
      "Noindex",
      "Noscript",
      "Output",
      "Picture",
      "Rp",
      "Rt",
      "Ruby",
      "S",
      "Samp",
      "Section",
      "Small",
      "Span",
      "Strong",
      "Sub",
      "Summary",
      "Sup",
      "Textarea",
      "Time",
      "U",
      "Var",
      "Wbr",
      "Webview"
    ],
    type: ControlType.Enum
  },
  margin: {
    title: "Margin",
    options: ["none", "dense"],
    optionTitles: ["None", "Dense"],
    type: ControlType.Enum
  },
  multiline: { title: "Multiline", type: ControlType.Boolean },
  name: { title: "Name", type: ControlType.String },
  placeholder: { title: "Placeholder", type: ControlType.String },
  readOnly: { title: "ReadOnly", type: ControlType.Boolean },
  required: { title: "Required", type: ControlType.Boolean },
  type: { title: "Type", type: ControlType.String }
});
