import * as React from "react";
import * as System from "@material-ui/core";
import { ControlType, PropertyControls, addPropertyControls } from "framer";

const style: React.CSSProperties = {
  width: "100%",
  height: "100%"
};

export const TableCell: React.SFC = props => {
  return <System.TableCell {...props} style={style} />;
};

TableCell.defaultProps = {
  width: 150,
  height: 50
};

addPropertyControls(TableCell, {
  align: {
    title: "Align",
    options: ["inherit", "center", "left", "right", "justify"],
    optionTitles: ["Inherit", "Center", "Left", "Right", "Justify"],
    type: ControlType.Enum
  },
  component: {
    title: "Component",
    options: [
      "abbr",
      "address",
      "article",
      "aside",
      "b",
      "bdi",
      "bdo",
      "big",
      "blockquote",
      "caption",
      "cite",
      "code",
      "data",
      "dd",
      "del",
      "details",
      "dfn",
      "div",
      "dt",
      "em",
      "figcaption",
      "figure",
      "footer",
      "h1",
      "h2",
      "h3",
      "h4",
      "h5",
      "h6",
      "head",
      "header",
      "hgroup",
      "i",
      "kbd",
      "keygen",
      "main",
      "mark",
      "menu",
      "menuitem",
      "meter",
      "nav",
      "noindex",
      "noscript",
      "output",
      "p",
      "picture",
      "rp",
      "rt",
      "ruby",
      "s",
      "samp",
      "section",
      "small",
      "span",
      "strong",
      "sub",
      "summary",
      "sup",
      "td",
      "th",
      "time",
      "u",
      "var",
      "wbr",
      "webview"
    ],
    optionTitles: [
      "Abbr",
      "Address",
      "Article",
      "Aside",
      "B",
      "Bdi",
      "Bdo",
      "Big",
      "Blockquote",
      "Caption",
      "Cite",
      "Code",
      "Data",
      "Dd",
      "Del",
      "Details",
      "Dfn",
      "Div",
      "Dt",
      "Em",
      "Figcaption",
      "Figure",
      "Footer",
      "H1",
      "H2",
      "H3",
      "H4",
      "H5",
      "H6",
      "Head",
      "Header",
      "Hgroup",
      "I",
      "Kbd",
      "Keygen",
      "Main",
      "Mark",
      "Menu",
      "Menuitem",
      "Meter",
      "Nav",
      "Noindex",
      "Noscript",
      "Output",
      "P",
      "Picture",
      "Rp",
      "Rt",
      "Ruby",
      "S",
      "Samp",
      "Section",
      "Small",
      "Span",
      "Strong",
      "Sub",
      "Summary",
      "Sup",
      "Td",
      "Th",
      "Time",
      "U",
      "Var",
      "Wbr",
      "Webview"
    ],
    type: ControlType.Enum
  },
  padding: {
    title: "Padding",
    options: ["default", "none", "checkbox"],
    optionTitles: ["Default", "None", "Checkbox"],
    type: ControlType.Enum
  },
  size: {
    title: "Size",
    options: ["small", "medium"],
    optionTitles: ["Small", "Medium"],
    type: ControlType.Enum
  },
  sortDirection: {
    title: "SortDirection",
    options: ["desc", "asc"],
    optionTitles: ["Desc", "Asc"],
    type: ControlType.Enum
  },
  variant: {
    title: "Variant",
    options: ["body", "footer", "head"],
    optionTitles: ["Body", "Footer", "Head"],
    type: ControlType.Enum
  }
});
